https:
  host: "0.0.0.0"
  port: "8082"
  timeout: "30000"
  path: "/api/*"
  
request-config:
  method: "GET"
  url: "https://api.first.org/data/v1/countries"
  
keystore:
  keyPassword: "![lNzQndTAmyquEyXfnL3Aqw==]"
  Password: "![lNzQndTAmyquEyXfnL3Aqw==]"
  path: "keystore.jks"
  type: JKS
 

